<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $countries = [
            [
                "id" => "1",
                "name" => "Albania",
                "currency" => "Leke",
                "code" => "ALL",
                "symbol" => "Lek",
            ],
            [
                "id" => "2",
                "name" => "America",
                "currency" => "Dollars",
                "code" => "USD",
                "symbol" => "$",
            ],
            [
                "id" => "3",
                "name" => "Afghanistan",
                "currency" => "Afghanis",
                "code" => "AF",
                "symbol" => "؋",
            ],
            [
                "id" => "4",
                "name" => "Argentina",
                "currency" => "Pesos",
                "code" => "ARS",
                "symbol" => "$",
            ],
            [
                "id" => "5",
                "name" => "Aruba",
                "currency" => "Guilders",
                "code" => "AWG",
                "symbol" => "ƒ",
            ],
            [
                "id" => "6",
                "name" => "Australia",
                "currency" => "Dollars",
                "code" => "AUD",
                "symbol" => "$",
            ],
            [
                "id" => "7",
                "name" => "Azerbaijan",
                "currency" => "New Manats",
                "code" => "AZ",
                "symbol" => "ман",
            ],
            [
                "id" => "8",
                "name" => "Bahamas",
                "currency" => "Dollars",
                "code" => "BSD",
                "symbol" => "$",
            ],
            [
                "id" => "9",
                "name" => "Barbados",
                "currency" => "Dollars",
                "code" => "BBD",
                "symbol" => "$",
            ],
            [
                "id" => "10",
                "name" => "Belarus",
                "currency" => "Rubles",
                "code" => "BYR",
                "symbol" => "p.",
            ],
            [
                "id" => "11",
                "name" => "Belgium",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "12",
                "name" => "Beliz",
                "currency" => "Dollars",
                "code" => "BZD",
                "symbol" => "BZ$",
            ],
            [
                "id" => "13",
                "name" => "Bermuda",
                "currency" => "Dollars",
                "code" => "BMD",
                "symbol" => "$",
            ],
            [
                "id" => "14",
                "name" => "Bolivia",
                "currency" => "Bolivianos",
                "code" => "BOB",
                "symbol" => '$b',
            ],
            [
                "id" => "15",
                "name" => "Bosnia and Herzegovina",
                "currency" => "Convertible Marka",
                "code" => "BAM",
                "symbol" => "KM",
            ],
            [
                "id" => "16",
                "name" => "Botswana",
                "currency" => "Pula's",
                "code" => "BWP",
                "symbol" => "P",
            ],
            [
                "id" => "17",
                "name" => "Bulgaria",
                "currency" => "Leva",
                "code" => "BG",
                "symbol" => "лв",
            ],
            [
                "id" => "18",
                "name" => "Brazil",
                "currency" => "Reais",
                "code" => "BRL",
                "symbol" => "R$",
            ],
            [
                "id" => "19",
                "name" => "Britain (United Kingdom)",
                "currency" => "Pounds",
                "code" => "GBP",
                "symbol" => "£",
            ],
            [
                "id" => "20",
                "name" => "Brunei Darussalam",
                "currency" => "Dollars",
                "code" => "BND",
                "symbol" => "$",
            ],
            [
                "id" => "21",
                "name" => "Cambodia",
                "currency" => "Riels",
                "code" => "KHR",
                "symbol" => "៛",
            ],
            [
                "id" => "22",
                "name" => "Canada",
                "currency" => "Dollars",
                "code" => "CAD",
                "symbol" => "$",
            ],
            [
                "id" => "23",
                "name" => "Cayman Islands",
                "currency" => "Dollars",
                "code" => "KYD",
                "symbol" => "$",
            ],
            [
                "id" => "24",
                "name" => "Chile",
                "currency" => "Pesos",
                "code" => "CLP",
                "symbol" => "$",
            ],
            [
                "id" => "25",
                "name" => "China",
                "currency" => "Yuan Renminbi",
                "code" => "CNY",
                "symbol" => "¥",
            ],
            [
                "id" => "26",
                "name" => "Colombia",
                "currency" => "Pesos",
                "code" => "COP",
                "symbol" => "$",
            ],
            [
                "id" => "27",
                "name" => "Costa Rica",
                "currency" => "Colón",
                "code" => "CRC",
                "symbol" => "₡",
            ],
            [
                "id" => "28",
                "name" => "Croatia",
                "currency" => "Kuna",
                "code" => "HRK",
                "symbol" => "kn",
            ],
            [
                "id" => "29",
                "name" => "Cuba",
                "currency" => "Pesos",
                "code" => "CUP",
                "symbol" => "₱",
            ],
            [
                "id" => "30",
                "name" => "Cyprus",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "31",
                "name" => "Czech Republic",
                "currency" => "Koruny",
                "code" => "CZK",
                "symbol" => "Kč",
            ],
            [
                "id" => "32",
                "name" => "Denmark",
                "currency" => "Kroner",
                "code" => "DKK",
                "symbol" => "kr",
            ],
            [
                "id" => "33",
                "name" => "Dominican Republic",
                "currency" => "Pesos",
                "code" => "DOP ",
                "symbol" => "RD$",
            ],
            [
                "id" => "34",
                "name" => "East Caribbean",
                "currency" => "Dollars",
                "code" => "XCD",
                "symbol" => "$",
            ],
            [
                "id" => "35",
                "name" => "Egypt",
                "currency" => "Pounds",
                "code" => "EGP",
                "symbol" => "£",
            ],
            [
                "id" => "36",
                "name" => "El Salvador",
                "currency" => "Colones",
                "code" => "SVC",
                "symbol" => "$",
            ],
            [
                "id" => "37",
                "name" => "England (United Kingdom)",
                "currency" => "Pounds",
                "code" => "GBP",
                "symbol" => "£",
            ],
            [
                "id" => "38",
                "name" => "Euro",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "39",
                "name" => "Falkland Islands",
                "currency" => "Pounds",
                "code" => "FKP",
                "symbol" => "£",
            ],
            [
                "id" => "40",
                "name" => "Fiji",
                "currency" => "Dollars",
                "code" => "FJD",
                "symbol" => "$",
            ],
            [
                "id" => "41",
                "name" => "France",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "42",
                "name" => "Ghana",
                "currency" => "Cedis",
                "code" => "GHC",
                "symbol" => "¢",
            ],
            [
                "id" => "43",
                "name" => "Gibraltar",
                "currency" => "Pounds",
                "code" => "GIP",
                "symbol" => "£",
            ],
            [
                "id" => "44",
                "name" => "Greece",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "45",
                "name" => "Guatemala",
                "currency" => "Quetzales",
                "code" => "GTQ",
                "symbol" => "Q",
            ],
            [
                "id" => "46",
                "name" => "Guernsey",
                "currency" => "Pounds",
                "code" => "GGP",
                "symbol" => "£",
            ],
            [
                "id" => "47",
                "name" => "Guyana",
                "currency" => "Dollars",
                "code" => "GYD",
                "symbol" => "$",
            ],
            [
                "id" => "48",
                "name" => "Holland (Netherlands)",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "49",
                "name" => "Honduras",
                "currency" => "Lempiras",
                "code" => "HNL",
                "symbol" => "L",
            ],
            [
                "id" => "50",
                "name" => "Hong Kong",
                "currency" => "Dollars",
                "code" => "HKD",
                "symbol" => "$",
            ],
            [
                "id" => "51",
                "name" => "Hungary",
                "currency" => "Forint",
                "code" => "HUF",
                "symbol" => "Ft",
            ],
            [
                "id" => "52",
                "name" => "Iceland",
                "currency" => "Kronur",
                "code" => "ISK",
                "symbol" => "kr",
            ],
            [
                "id" => "53",
                "name" => "India",
                "currency" => "Rupees",
                "code" => "INR",
                "symbol" => "Rp",
            ],
            [
                "id" => "54",
                "name" => "Indonesia",
                "currency" => "Rupiahs",
                "code" => "IDR",
                "symbol" => "Rp",
            ],
            [
                "id" => "55",
                "name" => "Iran",
                "currency" => "Rials",
                "code" => "IRR",
                "symbol" => "﷼",
            ],
            [
                "id" => "56",
                "name" => "Ireland",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "57",
                "name" => "Isle of Man",
                "currency" => "Pounds",
                "code" => "IMP",
                "symbol" => "£",
            ],
            [
                "id" => "58",
                "name" => "Israel",
                "currency" => "New Shekels",
                "code" => "ILS",
                "symbol" => "₪",
            ],
            [
                "id" => "59",
                "name" => "Italy",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "60",
                "name" => "Jamaica",
                "currency" => "Dollars",
                "code" => "JMD",
                "symbol" => "J$",
            ],
            [
                "id" => "61",
                "name" => "Japan",
                "currency" => "Yen",
                "code" => "JPY",
                "symbol" => "¥",
            ],
            [
                "id" => "62",
                "name" => "Jersey",
                "currency" => "Pounds",
                "code" => "JEP",
                "symbol" => "£",
            ],
            [
                "id" => "63",
                "name" => "Kazakhstan",
                "currency" => "Tenge",
                "code" => "KZT",
                "symbol" => "лв",
            ],
            [
                "id" => "64",
                "name" => "Korea (North)",
                "currency" => "Won",
                "code" => "KPW",
                "symbol" => "₩",
            ],
            [
                "id" => "65",
                "name" => "Korea (South)",
                "currency" => "Won",
                "code" => "KRW",
                "symbol" => "₩",
            ],
            [
                "id" => "66",
                "name" => "Kyrgyzstan",
                "currency" => "Soms",
                "code" => "KGS",
                "symbol" => "лв",
            ],
            [
                "id" => "67",
                "name" => "Laos",
                "currency" => "Kips",
                "code" => "LAK",
                "symbol" => "₭",
            ],
            [
                "id" => "68",
                "name" => "Latvia",
                "currency" => "Lati",
                "code" => "LVL",
                "symbol" => "Ls",
            ],
            [
                "id" => "69",
                "name" => "Lebanon",
                "currency" => "Pounds",
                "code" => "LBP",
                "symbol" => "£",
            ],
            [
                "id" => "70",
                "name" => "Liberia",
                "currency" => "Dollars",
                "code" => "LRD",
                "symbol" => "$",
            ],
            [
                "id" => "71",
                "name" => "Liechtenstein",
                "currency" => "Switzerland Francs",
                "code" => "CHF",
                "symbol" => "CHF",
            ],
            [
                "id" => "72",
                "name" => "Lithuania",
                "currency" => "Litai",
                "code" => "LTL",
                "symbol" => "Lt",
            ],
            [
                "id" => "73",
                "name" => "Luxembourg",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "74",
                "name" => "Macedonia",
                "currency" => "Denars",
                "code" => "MKD",
                "symbol" => "ден",
            ],
            [
                "id" => "75",
                "name" => "Malaysia",
                "currency" => "Ringgits",
                "code" => "MYR",
                "symbol" => "RM",
            ],
            [
                "id" => "76",
                "name" => "Malta",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "77",
                "name" => "Mauritius",
                "currency" => "Rupees",
                "code" => "MUR",
                "symbol" => "₨",
            ],
            [
                "id" => "78",
                "name" => "Mexico",
                "currency" => "Pesos",
                "code" => "MX",
                "symbol" => "$",
            ],
            [
                "id" => "79",
                "name" => "Mongolia",
                "currency" => "Tugriks",
                "code" => "MNT",
                "symbol" => "₮",
            ],
            [
                "id" => "80",
                "name" => "Mozambique",
                "currency" => "Meticais",
                "code" => "MZ",
                "symbol" => "MT",
            ],
            [
                "id" => "81",
                "name" => "Namibia",
                "currency" => "Dollars",
                "code" => "NAD",
                "symbol" => "$",
            ],
            [
                "id" => "82",
                "name" => "Nepal",
                "currency" => "Rupees",
                "code" => "NPR",
                "symbol" => "₨",
            ],
            [
                "id" => "83",
                "name" => "Netherlands Antilles",
                "currency" => "Guilders",
                "code" => "ANG",
                "symbol" => "ƒ",
            ],
            [
                "id" => "84",
                "name" => "Netherlands",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "85",
                "name" => "New Zealand",
                "currency" => "Dollars",
                "code" => "NZD",
                "symbol" => "$",
            ],
            [
                "id" => "86",
                "name" => "Nicaragua",
                "currency" => "Cordobas",
                "code" => "NIO",
                "symbol" => "C$",
            ],
            [
                "id" => "87",
                "name" => "Nigeria",
                "currency" => "Nairas",
                "code" => "NG",
                "symbol" => "₦",
            ],
            [
                "id" => "88",
                "name" => "North Korea",
                "currency" => "Won",
                "code" => "KPW",
                "symbol" => "₩",
            ],
            [
                "id" => "89",
                "name" => "Norway",
                "currency" => "Krone",
                "code" => "NOK",
                "symbol" => "kr",
            ],
            [
                "id" => "90",
                "name" => "Oman",
                "currency" => "Rials",
                "code" => "OMR",
                "symbol" => "﷼",
            ],
            [
                "id" => "91",
                "name" => "Pakistan",
                "currency" => "Rupees",
                "code" => "PKR",
                "symbol" => "₨",
            ],
            [
                "id" => "92",
                "name" => "Panama",
                "currency" => "Balboa",
                "code" => "PAB",
                "symbol" => "B/.",
            ],
            [
                "id" => "93",
                "name" => "Paraguay",
                "currency" => "Guarani",
                "code" => "PYG",
                "symbol" => "Gs",
            ],
            [
                "id" => "94",
                "name" => "Peru",
                "currency" => "Nuevos Soles",
                "code" => "PE",
                "symbol" => "S/.",
            ],
            [
                "id" => "95",
                "name" => "Philippines",
                "currency" => "Pesos",
                "code" => "PHP",
                "symbol" => "Php",
            ],
            [
                "id" => "96",
                "name" => "Poland",
                "currency" => "Zlotych",
                "code" => "PL",
                "symbol" => "zł",
            ],
            [
                "id" => "97",
                "name" => "Qatar",
                "currency" => "Rials",
                "code" => "QAR",
                "symbol" => "﷼",
            ],
            [
                "id" => "98",
                "name" => "Romania",
                "currency" => "New Lei",
                "code" => "RO",
                "symbol" => "lei",
            ],
            [
                "id" => "99",
                "name" => "Russia",
                "currency" => "Rubles",
                "code" => "RUB",
                "symbol" => "руб",
            ],
            [
                "id" => "100",
                "name" => "Saint Helena",
                "currency" => "Pounds",
                "code" => "SHP",
                "symbol" => "£",
            ],
            [
                "id" => "101",
                "name" => "Saudi Arabia",
                "currency" => "Riyals",
                "code" => "SAR",
                "symbol" => "﷼",
            ],
            [
                "id" => "102",
                "name" => "Serbia",
                "currency" => "Dinars",
                "code" => "RSD",
                "symbol" => "Дин.",
            ],
            [
                "id" => "103",
                "name" => "Seychelles",
                "currency" => "Rupees",
                "code" => "SCR",
                "symbol" => "₨",
            ],
            [
                "id" => "104",
                "name" => "Singapore",
                "currency" => "Dollars",
                "code" => "SGD",
                "symbol" => "$",
            ],
            [
                "id" => "105",
                "name" => "Slovenia",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "106",
                "name" => "Solomon Islands",
                "currency" => "Dollars",
                "code" => "SBD",
                "symbol" => "$",
            ],
            [
                "id" => "107",
                "name" => "Somalia",
                "currency" => "Shillings",
                "code" => "SOS",
                "symbol" => "S",
            ],
            [
                "id" => "108",
                "name" => "South Africa",
                "currency" => "Rand",
                "code" => "ZAR",
                "symbol" => "R",
            ],
            [
                "id" => "109",
                "name" => "South Korea",
                "currency" => "Won",
                "code" => "KRW",
                "symbol" => "₩",
            ],
            [
                "id" => "110",
                "name" => "Spain",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "111",
                "name" => "Sri Lanka",
                "currency" => "Rupees",
                "code" => "LKR",
                "symbol" => "₨",
            ],
            [
                "id" => "112",
                "name" => "Sweden",
                "currency" => "Kronor",
                "code" => "SEK",
                "symbol" => "kr",
            ],
            [
                "id" => "113",
                "name" => "Switzerland",
                "currency" => "Francs",
                "code" => "CHF",
                "symbol" => "CHF",
            ],
            [
                "id" => "114",
                "name" => "Suriname",
                "currency" => "Dollars",
                "code" => "SRD",
                "symbol" => "$",
            ],
            [
                "id" => "115",
                "name" => "Syria",
                "currency" => "Pounds",
                "code" => "SYP",
                "symbol" => "£",
            ],
            [
                "id" => "116",
                "name" => "Taiwan",
                "currency" => "New Dollars",
                "code" => "TWD",
                "symbol" => "NT$",
            ],
            [
                "id" => "117",
                "name" => "Thailand",
                "currency" => "Baht",
                "code" => "THB",
                "symbol" => "฿",
            ],
            [
                "id" => "118",
                "name" => "Trinidad and Tobago",
                "currency" => "Dollars",
                "code" => "TTD",
                "symbol" => "TT$",
            ],
            [
                "id" => "119",
                "name" => "Turkey",
                "currency" => "Lira",
                "code" => "TRY",
                "symbol" => "TL",
            ],
            [
                "id" => "120",
                "name" => "Turkey",
                "currency" => "Liras",
                "code" => "TRL",
                "symbol" => "£",
            ],
            [
                "id" => "121",
                "name" => "Tuvalu",
                "currency" => "Dollars",
                "code" => "TVD",
                "symbol" => "$",
            ],
            [
                "id" => "122",
                "name" => "Ukraine",
                "currency" => "Hryvnia",
                "code" => "UAH",
                "symbol" => "₴",
            ],
            [
                "id" => "123",
                "name" => "United Kingdom",
                "currency" => "Pounds",
                "code" => "GBP",
                "symbol" => "£",
            ],
            [
                "id" => "124",
                "name" => "United States of America",
                "currency" => "Dollars",
                "code" => "USD",
                "symbol" => "$",
            ],
            [
                "id" => "125",
                "name" => "Uruguay",
                "currency" => "Pesos",
                "code" => "UYU",
                "symbol" => '$U',
            ],
            [
                "id" => "126",
                "name" => "Uzbekistan",
                "currency" => "Sums",
                "code" => "UZS",
                "symbol" => "лв",
            ],
            [
                "id" => "127",
                "name" => "Vatican City",
                "currency" => "Euro",
                "code" => "EUR",
                "symbol" => "€",
            ],
            [
                "id" => "128",
                "name" => "Venezuela",
                "currency" => "Bolivares Fuertes",
                "code" => "VEF",
                "symbol" => "Bs",
            ],
            [
                "id" => "129",
                "name" => "Vietnam",
                "currency" => "Dong",
                "code" => "VND",
                "symbol" => "₫",
            ],
            [
                "id" => "130",
                "name" => "Yemen",
                "currency" => "Rials",
                "code" => "YER",
                "symbol" => "﷼",
            ],
            [
                "id" => "131",
                "name" => "Zimbabwe",
                "currency" => "Zimbabwe Dollars",
                "code" => "ZWD",
                "symbol" => "Z$",
            ]
        ];

        foreach($countries as $country){
            Country::create($country);
        }
    }
}
