<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguagesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = [
            ["id" => "1", "name" => "English", "iso_code" => "en"],
        ["id" => "2", "name" => "Afar", "iso_code" => "aa"],
        ["id" => "3", "name" => "Abkhazian", "iso_code" => "ab"],
        ["id" => "4", "name" => "Afrikaans", "iso_code" => "af"],
        ["id" => "5", "name" => "Amharic", "iso_code" => "am"],
        ["id" => "6", "name" => "Arabic", "iso_code" => "ar"],
        ["id" => "7", "name" => "Assamese", "iso_code" => "as"],
        ["id" => "8", "name" => "Aymara", "iso_code" => "ay"],
        ["id" => "9", "name" => "Azerbaijani", "iso_code" => "az"],
        ["id" => "10", "name" => "Bashkir", "iso_code" => "ba"],
        ["id" => "11", "name" => "Belarusian", "iso_code" => "be"],
        ["id" => "12", "name" => "Bulgarian", "iso_code" => "bg"],
        ["id" => "13", "name" => "Bihari", "iso_code" => "bh"],
        ["id" => "14", "name" => "Bislama", "iso_code" => "bi"],
        ["id" => "15", "name" => "Bengali/Bangla", "iso_code" => "bn"],
        ["id" => "16", "name" => "Tibetan", "iso_code" => "bo"],
        ["id" => "17", "name" => "Breton", "iso_code" => "br"],
        ["id" => "18", "name" => "Catalan", "iso_code" => "ca"],
        ["id" => "19", "name" => "Corsican", "iso_code" => "co"],
        ["id" => "20", "name" => "Czech", "iso_code" => "cs"],
        ["id" => "21", "name" => "Welsh", "iso_code" => "cy"],
        ["id" => "22", "name" => "Danish", "iso_code" => "da"],
        ["id" => "23", "name" => "German", "iso_code" => "de"],
        ["id" => "24", "name" => "Bhutani", "iso_code" => "dz"],
        ["id" => "25", "name" => "Greek", "iso_code" => "el"],
        ["id" => "26", "name" => "Esperanto", "iso_code" => "eo"],
        ["id" => "27", "name" => "Spanish", "iso_code" => "es"],
        ["id" => "28", "name" => "Estonian", "iso_code" => "et"],
        ["id" => "29", "name" => "Basque", "iso_code" => "eu"],
        ["id" => "30", "name" => "Persian", "iso_code" => "fa"],
        ["id" => "31", "name" => "Finnish", "iso_code" => "fi"],
        ["id" => "32", "name" => "Fiji", "iso_code" => "fj"],
        ["id" => "33", "name" => "Faeroese", "iso_code" => "fo"],
        ["id" => "34", "name" => "French", "iso_code" => "fr"],
        ["id" => "35", "name" => "Frisian", "iso_code" => "fy"],
        ["id" => "36", "name" => "Irish", "iso_code" => "ga"],
        ["id" => "37", "name" => "Scots/Gaelic", "iso_code" => "gd"],
        ["id" => "38", "name" => "Galician", "iso_code" => "gl"],
        ["id" => "39", "name" => "Guarani", "iso_code" => "gn"],
        ["id" => "40", "name" => "Gujarati", "iso_code" => "gu"],
        ["id" => "41", "name" => "Hausa", "iso_code" => "ha"],
        ["id" => "42", "name" => "Hindi", "iso_code" => "hi"],
        ["id" => "43", "name" => "Croatian", "iso_code" => "hr"],
        ["id" => "44", "name" => "Hungarian", "iso_code" => "hu"],
        ["id" => "45", "name" => "Armenian", "iso_code" => "hy"],
        ["id" => "46", "name" => "Interlingua", "iso_code" => "ia"],
        ["id" => "47", "name" => "Interlingue", "iso_code" => "ie"],
        ["id" => "48", "name" => "Inupiak", "iso_code" => "ik"],
        ["id" => "49", "name" => "Indonesian", "iso_code" => "in"],
        ["id" => "50", "name" => "Icelandic", "iso_code" => "is"],
        ["id" => "51", "name" => "Italian", "iso_code" => "it"],
        ["id" => "52", "name" => "Hebrew", "iso_code" => "iw"],
        ["id" => "53", "name" => "Japanese", "iso_code" => "ja"],
        ["id" => "54", "name" => "Yiddish", "iso_code" => "ji"],
        ["id" => "55", "name" => "Javanese", "iso_code" => "jw"],
        ["id" => "56", "name" => "Georgian", "iso_code" => "ka"],
        ["id" => "57", "name" => "Kazakh", "iso_code" => "kk"],
        ["id" => "58", "name" => "Greenlandic", "iso_code" => "kl"],
        ["id" => "59", "name" => "Cambodian", "iso_code" => "km"],
        ["id" => "60", "name" => "Kannada", "iso_code" => "kn"],
        ["id" => "61", "name" => "Korean", "iso_code" => "ko"],
        ["id" => "62", "name" => "Kashmiri", "iso_code" => "ks"],
        ["id" => "63", "name" => "Kurdish", "iso_code" => "ku"],
        ["id" => "64", "name" => "Kirghiz", "iso_code" => "ky"],
        ["id" => "65", "name" => "Latin", "iso_code" => "la"],
        ["id" => "66", "name" => "Lingala", "iso_code" => "ln"],
        ["id" => "67", "name" => "Laothian", "iso_code" => "lo"],
        ["id" => "68", "name" => "Lithuanian", "iso_code" => "lt"],
        ["id" => "69", "name" => "Latvian/Lettish", "iso_code" => "lv"],
        ["id" => "70", "name" => "Malagasy", "iso_code" => "mg"],
        ["id" => "71", "name" => "Maori", "iso_code" => "mi"],
        ["id" => "72", "name" => "Macedonian", "iso_code" => "mk"],
        ["id" => "73", "name" => "Malayalam", "iso_code" => "ml"],
        ["id" => "74", "name" => "Mongolian", "iso_code" => "mn"],
        ["id" => "75", "name" => "Moldavian", "iso_code" => "mo"],
        ["id" => "76", "name" => "Marathi", "iso_code" => "mr"],
        ["id" => "77", "name" => "Malay", "iso_code" => "ms"],
        ["id" => "78", "name" => "Maltese", "iso_code" => "mt"],
        ["id" => "79", "name" => "Burmese", "iso_code" => "my"],
        ["id" => "80", "name" => "Nauru", "iso_code" => "na"],
        ["id" => "81", "name" => "Nepali", "iso_code" => "ne"],
        ["id" => "82", "name" => "Dutch", "iso_code" => "nl"],
        ["id" => "83", "name" => "Norwegian", "iso_code" => "no"],
        ["id" => "84", "name" => "Occitan", "iso_code" => "oc"],
        ["id" => "85", "name" => "(Afan)/Oromoor/Oriya", "iso_code" => "om"],
        ["id" => "86", "name" => "Punjabi", "iso_code" => "pa"],
        ["id" => "87", "name" => "Polish", "iso_code" => "pl"],
        ["id" => "88", "name" => "Pashto/Pushto", "iso_code" => "ps"],
        ["id" => "89", "name" => "Portuguese", "iso_code" => "pt"],
        ["id" => "90", "name" => "Quechua", "iso_code" => "qu"],
        ["id" => "91", "name" => "Rhaeto-Romance", "iso_code" => "rm"],
        ["id" => "92", "name" => "Kirundi", "iso_code" => "rn"],
        ["id" => "93", "name" => "Romanian", "iso_code" => "ro"],
        ["id" => "94", "name" => "Russian", "iso_code" => "ru"],
        ["id" => "95", "name" => "Kinyarwanda", "iso_code" => "rw"],
        ["id" => "96", "name" => "Sanskrit", "iso_code" => "sa"],
        ["id" => "97", "name" => "Sindhi", "iso_code" => "sd"],
        ["id" => "98", "name" => "Sangro", "iso_code" => "sg"],
        ["id" => "99", "name" => "Serbo-Croatian", "iso_code" => "sh"],
        ["id" => "100", "name" => "Singhalese", "iso_code" => "si"],
        ["id" => "101", "name" => "Slovak", "iso_code" => "sk"],
        ["id" => "102", "name" => "Slovenian", "iso_code" => "sl"],
        ["id" => "103", "name" => "Samoan", "iso_code" => "sm"],
        ["id" => "104", "name" => "Shona", "iso_code" => "sn"],
        ["id" => "105", "name" => "Somali", "iso_code" => "so"],
        ["id" => "106", "name" => "Albanian", "iso_code" => "sq"],
        ["id" => "107", "name" => "Serbian", "iso_code" => "sr"],
        ["id" => "108", "name" => "Siswati", "iso_code" => "ss"],
        ["id" => "109", "name" => "Sesotho", "iso_code" => "st"],
        ["id" => "110", "name" => "Sundanese", "iso_code" => "su"],
        ["id" => "111", "name" => "Swedish", "iso_code" => "sv"],
        ["id" => "112", "name" => "Swahili", "iso_code" => "sw"],
        ["id" => "113", "name" => "Tamil", "iso_code" => "ta"],
        ["id" => "114", "name" => "Telugu", "iso_code" => "te"],
        ["id" => "115", "name" => "Tajik", "iso_code" => "tg"],
        ["id" => "116", "name" => "Thai", "iso_code" => "th"],
        ["id" => "117", "name" => "Tigrinya", "iso_code" => "ti"],
        ["id" => "118", "name" => "Turkmen", "iso_code" => "tk"],
        ["id" => "119", "name" => "Tagalog", "iso_code" => "tl"],
        ["id" => "120", "name" => "Setswana", "iso_code" => "tn"],
        ["id" => "121", "name" => "Tonga", "iso_code" => "to"],
        ["id" => "122", "name" => "Turkish", "iso_code" => "tr"],
        ["id" => "123", "name" => "Tsonga", "iso_code" => "ts"],
        ["id" => "124", "name" => "Tatar", "iso_code" => "tt"],
        ["id" => "125", "name" => "Twi", "iso_code" => "tw"],
        ["id" => "126", "name" => "Ukrainian", "iso_code" => "uk"],
        ["id" => "127", "name" => "Urdu", "iso_code" => "ur"],
        ["id" => "128", "name" => "Uzbek", "iso_code" => "uz"],
        ["id" => "129", "name" => "Vietnamese", "iso_code" => "vi"],
        ["id" => "130", "name" => "Volapuk", "iso_code" => "vo"],
        ["id" => "131", "name" => "Wolof", "iso_code" => "wo"],
        ["id" => "132", "name" => "Xhosa", "iso_code" => "xh"],
        ["id" => "133", "name" => "Yoruba", "iso_code" => "yo"],
        ["id" => "134", "name" => "Chinese", "iso_code" => "zh"],
        ["id" => "135", "name" => "Zulu", "iso_code" => "zu"],
        ];

        foreach($languages as $language){
            Language::create($language);
        }
    }
}
